name: 'aws-security-group-action'
description: 'aws-security-group-action'
branding:
  icon: unlock
  color: gray-dark
inputs:
  group-id: 
    description: 'ID of the security group'
    required: true
  action:
    description: 'Choose between "open" or "close"'
    required: false
    default: "open"
runs:
  using: "composite"
  steps:
    - name: Get IP
      run: |
        echo 'GAIP<<EOF' >> $GITHUB_ENV
        curl https://checkip.amazonaws.com >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      shell: bash
        
    - name: Add rule
      if: ${{ inputs.action == 'open' }}
      run: aws ec2 authorize-security-group-ingress --group-id ${{ inputs.group-id }} --protocol all --cidr ${{ env.GAIP }}/32
      shell: bash

    - name: Remove rule
      if: ${{ inputs.action == 'close' }}
      run: aws ec2 revoke-security-group-ingress --group-id ${{ inputs.group-id }} --protocol all --cidr ${{ env.GAIP }}/32
      shell: bash
